def app():
    import numpy as np
    import streamlit as st
    import pandas as pd

    st.title("Input - Output Model")
    with st.form(key = 'coefficients'):
        st.markdown('Now Let us enter Values of the different sectors')
        col1, col2, col3, col4 = st.columns(4)
        with col1:
            coef1_ind1 = st.text_input('Enter 1st coefficient of industry 1:',value=0.0)
        with col2:
            coef2_ind1 = st.text_input('Enter 2nd coefficient of industry 1:',value=0.0)
        with col3:
            coef1_ind2 = st.text_input('Enter 1st coefficient of industry 2:',value=0.0)
        with col4:
            coef2_ind2 = st.text_input('Enter 2nd coefficient of industry 2:',value=0.0)
        st.write(" ")
        st.write(" ")
        st.markdown('Now Let us enter Values of the expected Outputs')

        col1, col2 = st.columns(2)
        with col1:
            Out_ind1 = st.text_input(label='Enter Expected Output for industry 1:', max_chars=10,value=0.0)
        with col2:
            Out_ind2 = st.text_input(label='Enter Expected Output for industry 2:', max_chars=10,value=0.0)
        submit_but = st.form_submit_button()


    if submit_but:
        k = np.array([[coef1_ind1, coef2_ind1, Out_ind1],
                    [coef1_ind2, coef2_ind2, Out_ind2]])
        
        # Display the matrix using Streamlit
        st.write("Your Matrix is:")
        for row in k:
            row_string = " "
            for col in row:
                row_string += str(col) + "_"
            st.write(row_string)
        
        st.markdown("Which can also be displayed in a tabular form as: ")
        st.table(k)


    with st.form(key='Matrix_size'):
        col8, col9 = st.columns(2)
        with col8:
            row = st.number_input(label='Enter the number of rows of Matrix:', max_value=10,value=2)
        with col9:
            col = st.number_input(label='Enter the number of columns of Matrix:', max_value=10,value=2)

        submit_button = st.form_submit_button(label='Submit')

    if submit_button:
        # Process form submission
        st.write(f'You have a {row} X {col} Matrix')


    k = np.array([[coef1_ind1, coef2_ind1, Out_ind1],
                    [coef1_ind2, coef2_ind2, Out_ind2]])

    I = np.eye(row,col)

    # Changing our matrices to float
    F = k.astype(float)
    Q = I.astype(float)
    determinant = []
    for m in range(len(I)):
        row = []
        for n in range(len(I[0])):
            difference = Q[m][n] - F[m][n]
            row.append(difference)
        determinant.append(row)

    P = np.array([[Out_ind1],
                [Out_ind2]])
    floated_P = P.astype(float)
    st.title("The TOTAL OUTPUT generated by each sector are:")
    t = np.linalg.inv(determinant)
    floated_t = t.astype(float)
    Result = np.round(floated_t.dot(floated_P),2)
    print(f"Your final Output will be: {Result}")
    st.write(Result)
    st.write(f'The Output Level for first Sector ={Result[0]}')
    st.write(f'The Output Level for Second Sector ={Result[1]}')

